apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp-db
  labels:
    appdb: rsvpdb
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: rsvpdb
  template:
    metadata:
      labels:
        appdb: rsvpdb
    spec:
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongo-persistent-volume
      # volumes:
      # - name: mongodb-data
      #   hostPath:
      #     path: /data/db
      containers:
      - name: rsvp-db
        image: mongo:3.3
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db